App_SistemaGestionInventario/urls.py
from django.urls import path, include
from App_SistemaGestionInventario import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from .views import RegistroUsuario


urlpatterns = [
    path('', views.home, name="index_principal"),
    path('funciones_ingreso/', views.funciones_ingreso_rol, name='funciones_ingreso_rol'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('salir/',views.salir_sistema, name="salir"),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='App_SistemaGestionInventario/general/formulario.html'), name="password_reset"),
    path('reset_password_send/',auth_views.PasswordResetDoneView.as_view(template_name='App_SistemaGestionInventario/general/confirmacion_done.html'), name="password_reset_done"),
    path('reset_/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_completo/',auth_views.PasswordResetCompleteView.as_view(template_name='App_SistemaGestionInventario/general/contrasena_cambiada_exitosamente.html'), name="password_reset_complete"),


    #Permiso monitor    
    path('vista-permisos-monitor/', views.vista_permisos_monitor, name='vista_permisos_monitor'),    
    path('accion-permisos-todos/', views.accion_permisos_todos, name='accion_permisos_todos'),
    path('error-acceso-denegado/', views.error_acceso_denegado_monitor, name='error_acceso_denegado'),   
   

    #Plantillas generales
    
    path('index_info/', views.index_info, name="index_info"),



    #Plantillas administrador
    path('fun_admin/', views.funciones_administrador, name="funciones_administrador"),
    path('calen_admin/', views.calendario_administrador, name="calendario_administrador"),
    path('crear_usu/', RegistroUsuario.as_view(), name="crear_usuario"),
    path('reg_mate_admin/', views.registrar_materiales_administrador, name="registrar_materiales_administrador"),
    path('ver_usu/', views.visualizar_usuarios, name="visualizar_usuarios"),
    path('gene_repor_admin/', views.generar_reporte_admin, name="generar_reporte_admin"),
    path('dar_permi_admin/', views.vista_permisos_administrador, name="vista_permisos_administrador"),
    path('lis_mate_consu_admin/', views.listar_materiales_consumibles_administrador, name="listar_materiales_consumibles_administrador"),
    path('cuenta_admin/', views.visualizar_cuenta_administrador, name="visualizar_cuenta_administrador"),
    path('entre_consu_admin/', views.entregable_consumible_administrador, name="entregable_consumible_administrador"),
    path('entre_devo_admin/', views.entregable_devolutivo_administrador, name="entregable_devolutivo_administrador"),
    path('lis_mate_sup_admin/', views.listar_material_soporte_administrador, name="listar_material_soporte_administrador"),
    path('lis_mate_devo_admin/', views.listar_materiales_devolutivos_administrador, name="listar_materiales_devolutivos_administrador"),
    path('lis_mate_garan_admin/', views.listar_material_garantia_administrador, name="listar_material_garantia_administrador"),
    path('lis_mate_baja_admin/', views.listar_material_baja_administrador, name="listar_material_baja_administrador"),
    path('edi_mate_devo_admin/', views.editar_material_devolutivo_admininistrador, name="editar_material_devolutivo_admininistrador"),
    path('edi_mate_consu_admin/', views.editar_materiales_consumibles_administrador, name="editar_materiales_consumibles_administrador"),
    path('reto_devo_admin/', views.retornar_devolutivo_administrador, name="retornar_devolutivo_administrador"),
 

    #Plantillas instructor de planta
    path('fun_ins_planta/', views.funciones_instructor_planta, name="funciones_instructor_planta"),
    path('lis_usu_planta', views.lista_usuarios_planta, name="lista_usuarios"),
    path('regis_mate_ins_planta/', views.registrar_material_instructor_planta, name="registrar_material_instructor_planta"),
    path('lis_mate_consu_planta/', views.listar_materiales_consumibles_planta, name="listar_materiales_consumibles_planta"),
    path('lis_mate_devo_planta/', views.listar_materiales_devolutivos_planta, name="listar_materiales_devolutivos_planta"),
    path('calen_planta/', views.calendario_planta, name="calendario_planta"),
    path('dar_permi_planta/', views.vista_permisos_monitor_planta, name="vista_permisos_monitor_planta"),
    path('lis_mate_garan_planta/', views.listar_material_garantia_planta, name="listar_material_garantia_planta"),
    path('lis_mate_baja_planta/', views.listar_material_baja_planta, name="listar_material_baja_planta"),
    path('lis_mate_sopor_planta/', views.listar_material_soporte_planta, name="listar_material_soporte_planta"),
    path('entre_consu_planta/', views.entregable_consumible_planta, name="entregable_consumible_planta"),
    path('entre_devo_planta/', views.entregable_devolutivo_planta, name="entregable_devolutivo_planta"),
    path('ver_cuenta_planta/', views.visualizar_cuenta_planta, name="visualizar_cuenta_planta"),
    path('generar_reportes/', views.generar_reporte, name="generar_reporte"),
    path('generar-reporte-pdf/', views.generar_reporte_pdf_materiales, name='generar_reporte_pdf'),
    path('generar_excel/', views.generar_excel_materiales, name='generar_excel'),
    path('generar_excel_prestamo/', views.generar_excel_prestamo, name='generar_excel_prestamo'),
    path('generar_excel_consumible/', views.generar_excel_consumible, name='generar_excel_consumible'),
    path('generar_excel_clientes/', views.generar_excel_clientes, name='generar_excel_clientes'),
    path('generar_excel_usuario/', views.generar_excel_usuario, name='generar_excel_usuario'),
    path('reto_devo_planta/', views.retornar_devolutivo_planta, name="retornar_devolutivo_planta"),
    path('edi_mate_devo_planta/', views.editar_material_devolutivo_planta, name="editar_material_devolutivo_planta"),
    path('edi_mate_consu_planta/', views.editar_materiales_consumibles_planta, name="editar_materiales_consumibles_planta"),


    #Plantillas instructor de contrato
    path('fun_ins_contra/', views.funciones_instructor_contrato, name="funciones_instructor_contrato"),
    path('lis_usu_contra', views.listar_usuarios_contrato, name="lista_usuarios_contra"),
    path('regis_mate_ins_contra/', views.registrar_materiales_instructor_contrato, name="registrar_materiales_instructor_contrato"),
    path('calen_contra/', views.calendario_contrato, name="calendario_contrato"),
    path('lis_mate_baja_contra/', views.listar_material_baja_contrato, name="listar_material_baja_contrato"),
    path('lis_mate_consu_contra/', views.listar_material_consumible_contrato, name="listar_material_consumible_contrato"),
    path('lis_mate_devo_contra/', views.listar_material_devolutivo_contrato, name="listar_material_devolutivo_contrato"),
    path('lis_mate_garan_contra/', views.listar_material_garantia_contrato ,name="listar_material_garantia_contrato"),
    path('lis_mate_sup_contra/', views.listar_material_soporte_contrato, name="listar_material_soporte_contrato"),
    path('entre_consu_contra/', views.entregable_consumible_contrato, name="entregable_consumible_contrato"),
    path('entre_devo_contra/', views.entregable_devolutivo_contrato, name="entregable_devolutivo_contrato"),
    path('ver_cuenta_contra/', views.visualizar_cuenta_contra, name="visualizar_cuenta_contra"),
    path('reto_devo_contrato/', views.retornar_devolutivo_contrato, name="retornar_devolutivo_contrato"),
    path('edi_mate_consu_contra/', views.editar_materiales_consumibles_contratista, name="editar_materiales_consumibles_contratista"),
    path('edi_mate_devo_contra/', views.editar_materiales_devolutivos_contratista, name="editar_materiales_devolutivos_contratista"),

    #Plantillas monitor
    path('fun_moni/', views.funciones_monitor, name="funciones_monitor"),
    path('lis_mate_devo_moni/', views.listar_material_devolutivo_monitor, name="listar_material_devolutivo_monitor"),
    path('lis_mate_consu_moni/', views.listar_material_consumible_monitor, name="listar_material_consumible_monitor"), 
    path('calen_moni/', views.calendario_monitor, name="calendario_monitor"),
    path('regis_mate_moni/', views.registrar_material_monitor, name="registrar_material_monitor"),
    path('ver_cuenta_monitor/', views.visualizar_cuenta_monitor, name="visualizar_cuenta_monitor"),
    path('entre_consu_monitor/', views.entregable_consumible_monitor, name="entregable_consumible_monitor"),
    path('entre_devo_monitor/', views.entregable_devolutivo_monitor, name="entregable_devolutivo_monitor"),
    path('reto_devo_monitor/', views.retornar_material_devolutivo_monitor, name="retornar_material_devolutivo_monitor")

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Proyecto_SistemaGestionInventario/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('App_SistemaGestionInventario.urls')),
]

App_SistemaGestionInventario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from .choices import *

# Create your models here.

class CustomUser(AbstractUser):
    id = models.BigAutoField(primary_key = True)
    nombre_1 = models.CharField(max_length=80)
    nombre_2 = models.CharField(max_length=80, blank=True, null=True)
    apellido_1 = models.CharField(max_length=80)
    apellido_2 = models.CharField(max_length=80, blank=True, null=True)
    id_tipo_documento = models.CharField(max_length=11, choices=tipo_documento, default='C.C')
    numero_documento = models.CharField(max_length=80, blank=False, null=False, unique=True)
    correo_sena = models.EmailField(blank=True, null=True, unique=True)
    correo_soy_sena = models.EmailField(blank=False, null=False, unique=True)
    celular_1 = models.CharField(max_length=80, unique=True)
    celular_2 = models.CharField(max_length=80, blank=True, null=True)
    id_rol = models.CharField(max_length=5, choices=rol, default='I.C')
    fecha_inicio_contrato = models.DateField()
    fecha_fin_contrato = models.DateField(blank=True, null=True)
    id_area_instrtuctor = models.CharField(max_length=6, choices=area, default='Soft')
    firma_electronica = models.ImageField()
    permiso_monitor = models.BooleanField(default=False)
    estado_cuenta = models.CharField(max_length=1, choices=estado_cuenta_usuario, default='A')

    def nombre_completo(self):
        return "{} {}".format(self.nombre_1, self.apellido_1)

    def __str__(self):
        return self.nombre_completo()

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_groups',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_user_permissions',
        blank=True,
        help_text='Specific permissions for this user.',
        verbose_name='user permissions',
    )



class Materiales(models.Model):
    id = models.BigAutoField(primary_key = True)
    tipo_material = models.CharField(max_length=7, choices=tipo_material, default='Devo')
    nombre_material = models.CharField(max_length=40)
    modelo_material = models.CharField(max_length=40)
    ubicacion_material = models.CharField(max_length=7, choices=ubicacion_material, default='Z1')
    valor_material = models.IntegerField()
    estado_material = models.CharField(max_length=6, choices=estado_material, default="Dis")
    especificacion_tecnica_material = models.CharField(max_length=150)
    instructor_ecargado_material = models.ForeignKey(CustomUser, related_name='encargado_material', null=False, blank=False, on_delete=models.CASCADE)
    codigo_barras_original_material = models.CharField(max_length=50, blank=False, null=False, unique=True)
    codigo_barras_sena_material = models.CharField(max_length=50, blank=False, null=False, unique=True)
    encargado_registrar_material = models.ForeignKey(CustomUser, related_name='encargado_ingresar_consumible_sistema', null=False, blank=False, on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True, default='')
    fecha_ingreso_material = models.DateField(auto_now_add=True)
    actualizacion_material = models.DateField(auto_now_add=True)
    
    class Meta():
        verbose_name = 'Material'
        verbose_name_plural = 'Materiales'

    def material_instructor(self):
        return '{} - {} - {}'.format(self.nombre_material, self.codigo_barras_sena_material, self.instructor_ecargado_material)
    
    def __str__(self):
        return self.material_instructor()
    

class Clientes(models.Model):
    id = models.BigAutoField(primary_key=True)
    rol = models.CharField(max_length=5, choices=recibe_material, default='I.P')
    tipo_documento = models.CharField(max_length=11, choices=tipo_documento, default='C.C')
    numero_documento = models.IntegerField(blank=False, null=False, unique=True)
    primer_nombre = models.CharField(max_length=25, blank=False, null=False)
    segundo_nombre = models.CharField(max_length=25, blank=True, null=True)
    primer_apellido = models.CharField(max_length=25, blank=False, null=False)
    segundo_apellido = models.CharField(max_length=25, blank=True, null=True, )
    correo_soy_sena = models.EmailField( blank=False, null=False, default='')
    primer_telefono = models.CharField(max_length=20, blank=False, null=False, unique=True, default='')
    segundo_telefono = models.CharField(max_length=20,blank=True, null=True, default='')
    numero_ficha = models.CharField(max_length=20, blank=True, null=True)
    fecha_ingres_sistema = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'

    def nombre_cliente(self):
        return '{}  {} - {} - {}'.format(self.primer_nombre, self.primer_apellido, self.numero_documento, self.rol,)
    
    def __str__(self):
        return self.nombre_cliente()



class PrestamosConsumibles(models.Model):
    id = models.BigAutoField(primary_key=True)
    encargado_registra_prestamo_consumible = models.ForeignKey(CustomUser, blank=False, null=False, on_delete=models.CASCADE)    
    recibe_prestamo_prestamo_consumible = models.ForeignKey(Clientes, null=False, blank=False, on_delete=models.CASCADE)
    ubicacion_prestamo_prestamo_consumible = models.CharField(max_length=5, choices=ubicacion_material, default='N.A')
    material_otorgado_prestamo_consumible = models.ForeignKey(Materiales, null=False, blank=False, on_delete=models.CASCADE)
    fecha_entrega_prestamo_consumible = models.DateField(auto_now_add=True)

    class Meta():
        verbose_name = 'Prestamo consumible'
        verbose_name_plural = 'Prestamos Consumibles'
    
    def formato_prestamo(self):
        return '{} - {}'.format(self.id, self.material_otorgado_prestamo_consumible)

    def __str__(self):
        return self.formato_prestamo()



class PrestamosDevolutivos(models.Model):
    id = models.BigAutoField(primary_key=True)
    encargado_registra_material_devolutivo = models.ForeignKey(CustomUser, blank=False, null=False, on_delete=models.CASCADE)
    recibe_prestamo_material_devolutivo = models.ForeignKey(Clientes, blank=False, null=False, on_delete=models.CASCADE)
    ubicacion_prestamo_material_devolutivo = models.CharField(max_length=5, choices=ubicacion_material, default='Bod')
    material_otorgado_devolutivo = models.ForeignKey(Materiales, null=False, blank=False, on_delete=models.CASCADE)
    estado_prestamo = models.BooleanField(default=True)
    fecha_entrega_material_devolutivo = models.DateField(auto_now_add=True)
    fecha_devolucion_material_devolutivo = models.DateField(blank=False, null=False)

    class Meta():
        verbose_name = 'Prestamo Devolutivo'
        verbose_name_plural = 'Prestamos Devolutivos'

    def formato_prestamo(self):
        return '{} - {}'.format(self.id, self.material_otorgado_devolutivo)
    
    def __str__(self):
        return self.formato_prestamo()
    

App_SistemaGestionInventario/forms.py
from django import forms
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm

class DateInput(forms.DateInput):
    input_type = 'date'

class RegistroForm(UserCreationForm):
    fecha_inicio_contrato = forms.DateField(widget=DateInput(attrs={'readonly': 'readonly'}), required=False)
    fecha_fin_contrato = forms.DateField(widget=DateInput(attrs={'readonly': 'readonly'}), required=False)

    class Meta:
        model = CustomUser
        fields = ['username', 'nombre_1', 'nombre_2', 'apellido_1', 'apellido_2',
                  'id_tipo_documento', 'numero_documento', 'correo_sena', 'correo_soy_sena',
                  'celular_1', 'celular_2', 'id_rol', 'fecha_inicio_contrato',
                  'fecha_fin_contrato', 'id_area_instrtuctor', 'firma_electronica', 'estado_cuenta']
        widgets = {
            'fecha_inicio_contrato': DateInput(),
            'fecha_fin_contrato': DateInput(),
        }

class EditarPerfilForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['nombre_1', 'nombre_2', 'apellido_1', 'apellido_2', 'id_tipo_documento', 'numero_documento', 'correo_sena', 'correo_soy_sena', 'celular_1', 'celular_2', 'fecha_inicio_contrato', 'fecha_fin_contrato', 'firma_electronica']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Deshabilitar las fechas
        self.fields['fecha_inicio_contrato'].disabled = True
        self.fields['fecha_fin_contrato'].disabled = True

App_SistemaGestionInventario/templates/App_SistemaGestionInventario/instructor_contratista/base_instructor_contrato.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Automatización para las bodegas de software"> <!--Descripción de la página-->
    <meta name="keywords" content="Sistema Gestión Inventario"> <!--Corresponde a la identificación de palabras especiales-->
    <meta name="author" content="Ficha: 2503319, Angie Katherine Toro, Anderson Rincon Gomez, Mariana Henao Marin, Julio Cesar Orozco Lopez"> <!--Corresponde al autor de la pagina-->
    <link rel="shortcut icon" href="{% static 'App_SistemaGestionInventario/img/sena_contra.svg' %}">
    <link rel="stylesheet" href="{% static 'App_SistemaGestionInventario/css/plantilla_base_instructor_contratista_style.css' %}">
   

    {% block css %}

    {% endblock css %}
    <title>S.G.I</title>
</head>
<body>
    <header class="header">
        <div class="seccion-logo">
            <a class="logo" href="{% url 'funciones_instructor_contrato' %}"><img src="{% static 'App_SistemaGestionInventario/img/logo-sena-azul-actual-2022.svg' %}" alt="logo.sena"></a>
        </div>
        <div class="seccion-menu">
            <input type="checkbox" id="side-menu" class="side-menu">
            <label for="side-menu" class="menham"><span class="l-hamb"></span></label>
            <nav class="nav">
                <ul class="menu">
                    <li><a href="{% url 'calendario_contrato' %}">Calendario</a></li>
                    <li><a href="{% url 'registrar_materiales_instructor_contrato' %}">Registrar materiales</a></li>
                    <li><a href="{% url 'lista_usuarios_contra' %}">Usuarios</a></li>                                       
                </ul>
            </nav>
        </div>
        <div class="seccion-iconos">
            <div class="menu-container">
                <img src="{% static 'App_SistemaGestionInventario/img/usuario512px.png' %}" alt="Menú" class="menu-trigger" onclick="toggleMenu()">
                <ul class="dropdown-menu" id="myDropdown">
                    <li><a href="{% url 'visualizar_cuenta_contra' %}">Cuenta</a></li>
                    <li><a href="{% url 'salir' %}">Cerrar Sesión</a></li>
                </ul>
            </div>
        </div>

    </header>
    <a class="flecha" href="{% url 'funciones_instructor_contrato' %}">
        <img src="{% static 'App_SistemaGestionInventario/img/FlechaVolver.png' %}" alt="Volver">
    </a> 

    {% block content %}
    

    {% endblock %}
    <footer>
        <div class="contenedor-footer">
            <div class="contenedor-info">
                <h3 class="nombre-sena">Centro de Diseño e Innovación Tecnológica Industrial</h3>
                <span class="info-footer"><strong>Dosquebradas:</strong> 3430111</span>
                <span class="info-footer"><strong>Resto del país:</strong> 018000910270</span>
                <span class="info-footer"><strong>Horario de atención:</strong> Lunes a Viernes 7:00 AM a 7:00 PM</span>
            </div>
            <div class="contenedor-redes">
                <span class="titulo-redes-sociales">Redes Sociales</span>
                <div class="redes-sociales-contenedor">
                    <a href="https://web.facebook.com/SENARisaralda" class="link-social" target="_blank"></a>
                    <a href="https://www.instagram.com/senadosquebradas/?hl=es" class="link-social" target="_blank"></a>
                    <a href="https://www.linkedin.com/school/servicio-nacional-de-aprendizaje-sena-/" class="link-social" target="_blank"></a>
                    <a href="https://www.tiktok.com/@senacomunica_" class="link-social" target="_blank"></a>
                    <a href="https://twitter.com/SENAComunica" class="link-social" target="_blank"></a>
                    <a href="https://api.whatsapp.com/send/?phone=573168760255&text&app_absent=0" class="link-social" target="_blank"></a>
                </div>
            </div>
        </div>
        <div class="contenedor-copyright">
            <center>
                <span class="copyright">&copy;2023, Ficha 2503319 <br> Anderson Rincón Gómez, Angie Katherine Toro Echeverri, Julio Cesar Orozco López, Mariana Henao Marín</span><!-- Aviso de derechos de autor con el año y número de ficha -->
            </center>
        </div>
    </footer>
    <script src="{% static "App_SistemaGestionInventario/js/base_administrador_script.js" %}"></script>
</body>
</html>

App_SistemaGestionInventario/templates/App_SistemaGestionInventario/instructor_contratista/ver_perfil_contra.html
{% extends "App_SistemaGestionInventario/instructor_contratista/base_instructor_contrato.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'App_SistemaGestionInventario/css/ver_perfil_contra_style.css' %}">
{% endblock css %}

{% block content %}

<main>

    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>Error:</strong> Por favor, corrija los siguientes errores del formulario.
        <ul>
            {% for field, errors in form.errors.items %}
                {% if field == 'fecha_inicio_contrato' %}
                    {% for error in errors %}
                        <li>{{ field|title }}: {{ error }}</li>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

    <h2>Datos personales</h2>
    <form action="{% url 'visualizar_cuenta_contra' %}" class="formulario-crear-material" id="crear-materialForm" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    
        {{ form.nombre_1.errors }}
        <input type="text" name="nombre_1" value="{{ form.nombre_1.value|default:'' }}" placeholder="Primer nombre">
        
        {{ form.nombre_2.errors }}
        <input type="text" name="nombre_2" value="{{ form.nombre_2.value|default:'' }}" placeholder="Segundo Nombre">
        
        {{ form.apellido_1.errors }}
        <input type="text" name="apellido_1" value="{{ form.apellido_1.value|default:'' }}" placeholder="Primer Apellido">
        
        {{ form.apellido_2.errors }}
        <input type="text" name="apellido_2" value="{{ form.apellido_2.value|default:'' }}" placeholder="Segundo Apellido">
    
        <div class="contenedor-desplegable-documento">
            <label for="id_tipo_documento">Tipo de identificación:</label>
            {{ form.id_tipo_documento.errors }}
            <select name="id_tipo_documento" placeholder="Tipo de Identificacion" readonly>
                <option value="C.C" {% if form.id_tipo_documento.value == 'C.C' %}selected{% endif %}>C.C</option>            
            </select>
        </div>
    
        <input type="text" name="numero_documento" value="{{ form.numero_documento.value|default:'' }}" placeholder="Numero de Identificacion" readonly>
        
        {{ form.correo_sena.errors }}
        <input type="text" name="correo_sena" value="{{ form.correo_sena.value|default:'' }}" placeholder="Correo Sena">
        
        {{ form.correo_soy_sena.errors }}
        <input type="text" name="correo_soy_sena" value="{{ form.correo_soy_sena.value|default:'' }}" placeholder="Correo Soy Sena">
        
        {{ form.celular_1.errors }}
        <input type="text" name="celular_1" value="{{ form.celular_1.value|default:'' }}" placeholder="Numero de Telefono">                                                
        
        {{ form.celular_2.errors }}
        <input type="text" name="celular_2" value="{{ form.celular_2.value|default:'' }}" placeholder="Numero de Telefono (opcional)">
            
        
        <div class="contenedor-desplegable-documento">
            <div class="fecha-item">
                <label for="id_fecha_inicio_contrato">Fecha de Inicio:</label>
                {{ form.fecha_inicio_contrato.value|default:'' }}
            </div>
            <div class="fecha-item">
                <label for="id_fecha_fin_contrato">Fecha Fin:</label>
                {{ form.fecha_fin_contrato.value|default:'' }}
            </div>
        </div>
                
        
        {{ form.firma_electronica.errors }}
        <input type="file" name="firma_electronica" accept="image/*">
            
    
        <div class="boton">
            <button type="submit">Editar Perfil</button>
        </div>
    </form>
</main>

{% endblock content %}